In [1]:
#importing libraries
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.width', 1000)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

## Data Processing

In [9]:
#loading the trippub data
df = pd.read_csv('/Users/syedfaquaruddinquadri/Documents/research_project/NHTS/trippub.csv')
df.head(10)

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,VEHID,TRWAITTM,NUMTRANS,TRACCTM,DROP_PRK,TREGRTM,WHODROVE,WHYFROM,LOOP_TRIP,TRPHHVEH,HHMEMDRV,HH_ONTD,NONHHCNT,NUMONTRP,PSGR_FLG,PUBTRANS,TRIPPURP,DWELTIME,TDWKND,VMT_MILE,DRVR_FLG,WHYTRP1S,ONTD_P1,ONTD_P2,ONTD_P3,ONTD_P4,ONTD_P5,ONTD_P6,ONTD_P7,ONTD_P8,ONTD_P9,ONTD_P10,ONTD_P11,ONTD_P12,ONTD_P13,TDCASEID,TRACC_WLK,TRACC_POV,TRACC_BUS,TRACC_CRL,TRACC_SUB,TRACC_OTH,TREGR_WLK,TREGR_POV,TREGR_BUS,TREGR_CRL,TREGR_SUB,TREGR_OTH,WHYTO,TRAVDAY,HOMEOWN,HHSIZE,HHVEHCNT,HHFAMINC,DRVRCNT,HHSTATE,HHSTFIPS,NUMADLT,WRKCOUNT,TDAYDATE,HHRESP,LIF_CYC,MSACAT,MSASIZE,RAIL,URBAN,URBANSIZE,URBRUR,GASPRICE,CENSUS_D,CENSUS_R,CDIVMSAR,HH_RACE,HH_HISP,HH_CBSA,SMPLSRCE,R_AGE,EDUC,R_SEX,PRMACT,PROXY,WORKER,DRIVER,WTTRDFIN,WHYTRP90,TRPMILAD,R_AGE_IMP,R_SEX_IMP,VEHTYPE,OBHUR,DBHUR,OTHTNRNT,OTPPOPDN,OTRESDN,OTEEMPDN,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
0,30000007,1,1,1000,1015,15,5.244,3,0,0,3,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBO,295,2,5.244,1,20,1,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000070101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,19,2,1,3,5,7,3,NC,37,3,1,201608,1,10,3,1,2,1,1,1,228.4,5,3,53,2,2,XXXXX,2,67,3,2,6,1,2,1,75441.905796,5,5.847584,67,2,1,T,T,50,1500,750,750,20,750,300,50,750,300,350,30,300,300
1,30000007,1,2,1510,1530,20,5.149,3,0,0,3,-1,-1,-1,-1,-1,1,19,2,1,1,1,0,1,2,2,HBO,-9,2,5.149,1,1,1,2,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000070102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,2,1,3,5,7,3,NC,37,3,1,201608,1,10,3,1,2,1,1,1,228.4,5,3,53,2,2,XXXXX,2,67,3,2,6,1,2,1,75441.905796,5,5.741650,67,2,1,T,T,50,750,300,350,30,300,300,50,1500,750,750,20,750,300
2,30000007,2,1,700,900,120,84.004,6,0,0,5,-1,-1,-1,-1,-1,2,3,2,1,1,1,0,1,2,2,HBW,540,2,84.004,1,1,2,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000070201,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,2,1,3,5,7,3,NC,37,3,1,201608,1,10,3,1,2,1,1,1,228.4,5,3,53,2,2,XXXXX,2,66,3,1,1,2,1,1,71932.645806,1,90.178294,66,1,4,S,T,40,1500,750,750,40,1500,750,50,1500,750,750,20,750,300
3,30000007,2,2,1800,2030,150,81.628,6,0,0,5,-1,-1,-1,-1,-1,2,1,2,1,1,1,0,1,2,2,HBW,-9,2,81.628,1,10,2,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000070202,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,2,1,3,5,7,3,NC,37,3,1,201608,1,10,3,1,2,1,1,1,228.4,5,3,53,2,2,XXXXX,2,66,3,1,1,2,1,1,71932.645806,1,87.627658,66,1,4,T,S,50,1500,750,750,20,750,300,40,1500,750,750,40,1500,750
4,30000007,3,1,845,900,15,2.250,3,0,0,1,-1,-1,-1,-1,-1,3,1,2,1,1,1,0,1,2,2,HBO,330,2,2.250,1,20,2,2,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000070301,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,8,2,1,3,5,7,3,NC,37,3,1,201608,1,10,3,1,2,1,1,1,228.4,5,3,53,2,2,XXXXX,2,28,2,2,5,2,2,1,80122.686739,5,2.508975,28,2,1,T,T,50,1500,750,750,20,750,300,50,750,300,350,60,750,300
5,30000007,3,2,1430,1445,15,2.243,3,0,0,1,-1,-1,-1,-1,-1,3,8,2,1,1,1,0,1,2,2,HBO,-9,2,2.243,1,1,2,2,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000070302,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,2,1,3,5,7,3,NC,37,3,1,201608,1,10,3,1,2,1,1,1,228.4,5,3,53,2,2,XXXXX,2,28,2,2,5,2,2,1,80122.686739,5,2.501169,28,2,1,T,T,50,750,300,350,60,750,300,50,1500,750,750,20,750,300
6,30000008,1,1,1115,1130,15,8.017,6,0,0,4,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBW,720,2,8.017,1,10,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000080101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,5,1,2,4,8,2,WI,55,2,2,201608,2,2,2,5,2,4,6,2,225.9,3,2,32,1,2,33460,2,55,5,1,1,1,1,1,23062.857428,1,8.606250,55,1,4,R,T,5,300,300,150,5,300,300,30,300,300,150,40,1500,750
7,30000008,1,2,2330,2340,10,8.017,6,0,0,4,-1,-1,-1,-1,-1,1,3,2,1,1,1,0,1,2,2,HBW,-9,2,8.017,1,1,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000080102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,2,4,8,2,WI,55,2,2,201608,2,2,2,5,2,4,6,2,225.9,3,2,32,1,2,33460,2,55,5,1,1,1,1,1,23062.857428,1,8.606250,55,1,4,T,R,30,300,300,150,40,1500,750,5,300,300,150,5,300,300
8,30000012,1,1,550,605,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,55,2,3.395,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,C,S,80,17000,17000,5000,60,17000,7000,30,750,300,350,5,750,300
9,30000012,1,2,700,715,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,16,2,1,1,1,0,1,2,2,HBSOCREC,15,2,3.395,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,S,C,30,750,300,350,5,750,300,80,17000,17000,5000,60,17000,7000

In [57]:
#checking the shape of the data
df.shape

(923572, 115)

In [11]:
#cheching the observation in ny
list_of_states = df['HHSTATE'].unique()
print(list_of_states)

#cheeching the oberrvation only in NY
ny_df = df[df['HHSTATE'] == 'NY']
#cheeching the oberrvation only in NJ
nj_df = df[df['HHSTATE'] == 'NJ']

['NC' 'WI' 'NY' 'MD' 'PA' 'CA' 'TX' 'ME' 'AZ' 'WA' 'AL' 'IL' 'KY' 'MT'
 'IA' 'GA' 'VA' 'SC' 'WV' 'FL' 'NH' 'MN' 'NE' 'AR' 'NJ' 'SD' 'NM' 'OK'
 'MI' 'VT' 'ID' 'DE' 'TN' 'MA' 'WY' 'CO' 'IN' 'HI' 'AK' 'OH' 'RI' 'LA'
 'ND' 'OR' 'KS' 'UT' 'MO' 'DC' 'NV' 'MS' 'CT']

In [59]:
#printing the shape of the nj and ny
print(f"Shape of NJ is {nj_df.shape}")
print(f"Shape of NY is {ny_df.shape}")

Shape of NJ is (4140, 115)
Shape of NY is (120207, 115)

In [60]:
#checking the ny data 
ny_df.head(10)

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,VEHID,TRWAITTM,NUMTRANS,TRACCTM,DROP_PRK,TREGRTM,WHODROVE,WHYFROM,LOOP_TRIP,TRPHHVEH,HHMEMDRV,HH_ONTD,NONHHCNT,NUMONTRP,PSGR_FLG,PUBTRANS,TRIPPURP,DWELTIME,TDWKND,VMT_MILE,DRVR_FLG,WHYTRP1S,ONTD_P1,ONTD_P2,ONTD_P3,ONTD_P4,ONTD_P5,ONTD_P6,ONTD_P7,ONTD_P8,ONTD_P9,ONTD_P10,ONTD_P11,ONTD_P12,ONTD_P13,TDCASEID,TRACC_WLK,TRACC_POV,TRACC_BUS,TRACC_CRL,TRACC_SUB,TRACC_OTH,TREGR_WLK,TREGR_POV,TREGR_BUS,TREGR_CRL,TREGR_SUB,TREGR_OTH,WHYTO,TRAVDAY,HOMEOWN,HHSIZE,HHVEHCNT,HHFAMINC,DRVRCNT,HHSTATE,HHSTFIPS,NUMADLT,WRKCOUNT,TDAYDATE,HHRESP,LIF_CYC,MSACAT,MSASIZE,RAIL,URBAN,URBANSIZE,URBRUR,GASPRICE,CENSUS_D,CENSUS_R,CDIVMSAR,HH_RACE,HH_HISP,HH_CBSA,SMPLSRCE,R_AGE,EDUC,R_SEX,PRMACT,PROXY,WORKER,DRIVER,WTTRDFIN,WHYTRP90,TRPMILAD,R_AGE_IMP,R_SEX_IMP,VEHTYPE,OBHUR,DBHUR,OTHTNRNT,OTPPOPDN,OTRESDN,OTEEMPDN,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
8,30000012,1,1,550,605,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,55,2,3.395,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,C,S,80,17000,17000,5000,60,17000,7000,30,750,300,350,5,750,300
9,30000012,1,2,700,715,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,16,2,1,1,1,0,1,2,2,HBSOCREC,15,2,3.395,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,S,C,30,750,300,350,5,750,300,80,17000,17000,5000,60,17000,7000
10,30000012,1,3,730,740,10,1.059,4,0,0,2,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,25,2,1.059,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120103,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,1.180891,45,2,3,C,C,80,17000,17000,5000,60,17000,7000,70,17000,7000,5000,90,3000,1500
11,30000012,1,4,805,815,10,1.014,4,0,0,2,-1,-1,-1,-1,-1,1,16,2,1,1,1,0,1,2,2,HBSOCREC,45,2,1.014,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120104,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,1.130711,45,2,3,C,C,70,17000,7000,5000,90,3000,1500,80,17000,17000,5000,60,17000,7000
12,30000012,1,5,900,920,20,4.291,3,0,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBW,295,2,4.291,1,10,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120105,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,2,4.784894,45,2,1,C,S,80,17000,17000,5000,60,17000,7000,20,1500,750,750,20,3000,1500
13,30000012,1,6,1415,1440,25,9.087,3,0,0,1,-1,-1,-1,-1,-1,1,4,2,1,1,1,0,1,2,2,NHB,50,2,9.087,1,10,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120106,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,1,9.754895,45,2,1,S,S,20,1500,750,750,20,3000,1500,20,1500,750,750,0,1500,750
14,30000012,1,7,1530,1605,35,6.818,3,0,0,1,-1,-1,-1,-1,-1,1,3,2,1,1,1,0,1,2,2,HBW,70,2,6.818,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120107,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,1,7.319123,45,2,1,S,C,20,1500,750,750,0,1500,750,80,17000,17000,5000,60,17000,7000
15,30000012,1,8,1715,1850,95,48.301,3,0,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,125,2,48.301,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120108,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,17,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,8,53.860445,45,2,1,C,T,80,17000,17000,5000,60,17000,7000,5,750,300,350,20,1500,750
16,30000012,1,9,2055,2145,50,49.457,3,0,0,1,-1,-1,-1,-1,-1,1,17,2,1,1,1,0,1,2,2,HBSOCREC,-9,2,49.457,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120109,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,8,55.149501,45,2,1,T,C,5,750,300,350,20,1500,750,80,17000,17000,5000,60,17000,7000
54,30000082,1,1,745,752,7,2.710,3,2,2,2,-1,-1,-1,-1,-1,1,1,2,1,1,3,0,3,2,2,HBO,17,2,2.710,1,70,1,2,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000820101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,6,3,2,4,2,8,2,NY,36,2,2,201605,1,4,3,3,2,1,3,1,241.3,2,1,23,1,2,XXXXX,2,39,5,2,1,1,1,1,375517.390495,4,3.021921,39,2,1,T,T,20,1500,300,750,30,750,300,40,1500,750,750,5,300,300

In [22]:
#checking if puerto rico is in the data
df[df['HHSTATE'] == 'PR']

#there is no puerto rico in the data

Empty DataFrame
Columns: [HOUSEID, PERSONID, TDTRPNUM, STRTTIME, ENDTIME, TRVLCMIN, TRPMILES, TRPTRANS, TRPACCMP, TRPHHACC, VEHID, TRWAITTM, NUMTRANS, TRACCTM, DROP_PRK, TREGRTM, WHODROVE, WHYFROM, LOOP_TRIP, TRPHHVEH, HHMEMDRV, HH_ONTD, NONHHCNT, NUMONTRP, PSGR_FLG, PUBTRANS, TRIPPURP, DWELTIME, TDWKND, VMT_MILE, DRVR_FLG, WHYTRP1S, ONTD_P1, ONTD_P2, ONTD_P3, ONTD_P4, ONTD_P5, ONTD_P6, ONTD_P7, ONTD_P8, ONTD_P9, ONTD_P10, ONTD_P11, ONTD_P12, ONTD_P13, TDCASEID, TRACC_WLK, TRACC_POV, TRACC_BUS, TRACC_CRL, TRACC_SUB, TRACC_OTH, TREGR_WLK, TREGR_POV, TREGR_BUS, TREGR_CRL, TREGR_SUB, TREGR_OTH, WHYTO, TRAVDAY, HOMEOWN, HHSIZE, HHVEHCNT, HHFAMINC, DRVRCNT, HHSTATE, HHSTFIPS, NUMADLT, WRKCOUNT, TDAYDATE, HHRESP, LIF_CYC, MSACAT, MSASIZE, RAIL, URBAN, URBANSIZE, URBRUR, GASPRICE, CENSUS_D, CENSUS_R, CDIVMSAR, HH_RACE, HH_HISP, HH_CBSA, SMPLSRCE, R_AGE, EDUC, R_SEX, PRMACT, PROXY, WORKER, DRIVER, WTTRDFIN, WHYTRP90, TRPMILAD, R_AGE_IMP, R_SEX_IMP, VEHTYPE, OBHUR, ...]
Index: []

In [23]:
#checking the unique household id
print(len(df['HOUSEID'].unique()))

117222

In [25]:
#listing all the columns in the data
# col = df.columns.tolist()
# col

In [ ]:
#HHSTFIPS- state code
#new york state code 36
#new jersey state code 34
#puerto rico state code 72


#list of the columns and there labels
# HOUSEID - unique household id
# PERSONID - personid in the household
# TDTRPNUM - incrementing travel day trip number, starting at 1 for each person in the file
# STRTTIME - start time of the trip
# ENDTIME - end time of the trip
# TRVLCMIN - travel time in minutes
# TRPMILES - travel miles
# TRPTRANS - mode of transport
# TRPACCMP - count of people on the trip
# TRPHHACC - count of household members on the trip
# VEHID - vehicle id in the household
# TRWAITTM - transit wait time in minutes
# NUMTRANS - count of transfers
# TRACCTM - trip time to transit station in minutes
# DROP_PRK - parked or dropped off
# TREGRTM - time to destination from transit in minutes
# WHODROVE - person who drove the vehicle
# WHYFROM - reason for previous trip
# LOOP_TRIP - trip origin and destination at identical location
# TRPHHVEH - household vehicle used for the trip
# HHMEMDRV - household member who drove the vehicle
# HH_ONTD - number of household members on the trip including respondent
# NONHHCNT - number of non-household members on the trip
# NUMONTRP - number of people on the trip
# PSGR_FLG - flag for passenger on the trip
# PUBTRANS - used public transport for the trip
# TRIPPURP - general purpose of the trip
# DWELTIME - time at the destination
# TDWKND - weekend trip
# VMT_MILE - calculated trip distance for driver trips
# DRVR_FLG - flag for driver on trip
# WHYTRP1S - trip purpose summary
# ONTD_P1 - person 1 was on trip
# ONTD_P2 - person 2 was on trip
# ONTD_P3 - person 3 was on trip
# ONTD_P4 - person 4 was on trip
# ONTD_P5 - person 5 was on trip
# ONTD_P6 - person 6 was on trip
# ONTD_P7 - person 7 was on trip
# ONTD_P8 - person 8 was on trip
# ONTD_P9 - person 9 was on trip
# ONTD_P10 - person 10 was on trip
# ONTD_P11 - person 11 was on trip
# ONTD_P12 - person 12 was on trip
# ONTD_P13 - person 13 was on trip
# TDCASEID - unique identifier for every trip in the file 
# TRACC_WLK - walk as mode used to get to public transit
# TRACC_POV - POV as mode used to get to public transit
# TRACC_BUS - Bus as mode used to get to public transit
# TRACC_CRL - RAIL as mode used to get to public transit
# TRACC_SUB - SUBWAY as mode used to get to public transit
# TRACC_OTH - Other as mode used to get to public transit
# TREGR_WLK - WALK as mode used to get to the PUBLIC TRANSIT
# TREGR_POV - POV as mode used to get to the PUBLIC TRANSIT
# TREGR_BUS - BUS as mode used to get to the PUBLIC TRANSIT
# TREGR_CRL - rail as mode used to get to the PUBLIC TRANSIT
# TREGR_SUB - subway as mode used to get to the PUBLIC TRANSIT
# TREGR_OTH - other mode used to get to the PUBLIC TRANSIT
# WHYTO - reason for the travel to the destination
# TRAVDAY - travel day of the week
# HOMEOWN - whether home owned or rented 
# HHSIZE - total number in the household
# HHVEHCNT - total number of vehicles in the household
# HHFAMINC - household income
# DRVRCNT - number of drivers in the household
# HHSTATE - household state
# HHSTFIPS - state FIPS for household
# NUMADLT - count of adult members in the household atleast 18 years old
# WRKCOUNT - count of workers in the household
# TDAYDATE - Date of travel day (YYYYMM)
# HHRESP - person identifier of the household respondent
# LIF_CYC - life cycle classification for the household
# MSACAT - MSA category for the household home address
# MSASIZE - population size category of the MSA from the five-year ACS API
# RAIL - MSA heavy rail status
# URBAN - household urban status
# URBANSIZE - urban area size where home address is located
# URBRUR - household urban/rural area
# GASPRICE - weekyly average gas price in cents, during the week of travel day
# CENSUS_D - census division classification for the home address
# CENSUS_R - census region classification for the home address
# CDIVMSAR - grouping of household by combination of census division, MSA status, and presence of rail
# HH_RACE - race of household respondent
# HH_HISP - hispanic status of the household respondent
# HH_CBSA - core based statistical area FIPS code for the respondents home address
# SMPLSRCE - sample where the case originated
# R_AGE - respondent age
# EDUC - highest level of education
# R_SEX - respondent sex
# PRMACT - primary activity for those who did not work for pay last week
# PROXY - survey completed by self or someone else
# WORKER - employment status of the respondent 
# DRIVER - driver status, derived
# WTTRDFIN - 7-daynatl household weight
# WHYTRP90 - Travel day trip purpose consistent with 1990 NPTS design
# TRPMILAD - 
# R_AGE_IMP - age imputed
# R_SEX_IMP - respondent sex (imputed)
# VEHTYPE - vehicle type
# OBHUR - 
# DBHUR
# OTHTNRNT
# OTPPOPDN
# OTRESDN
# OTEEMPDN
# OBHTNRNT
# OBPPOPDN
# OBRESDN
# DTHTNRNT
# DTPPOPDN
# DTRESDN
# DTEEMPDN
# DBHTNRNT
# DBPPOPDN
# DBRESDN

In [10]:
#selecting the rows with urban status as 1, 2, 3
urban_ny = ny_df[ny_df['URBAN'].isin([1,2,3])]
urban_ny.shape

NameError: name 'ny_df' is not defined

In [ ]:
urban_ny[urban_ny['CENSUS_D']==

In [72]:
urban_ny[['CENSUS_D', 'HHSTATE']].head(50)

urban_ny[urban_ny['CENSUS_D']==5]

#selecting CENSUS_D as 5 and HHSTATE as NY
print(urban_ny[urban_ny['CENSUS_D']==2].shape)

print(urban_ny[urban_ny['HHSTATE']=='NY'].shape)


#what are the CENSUS_D values

(83330, 115)
(83369, 115)

In [9]:
urban_nj = nj_df[nj_df['URBAN'].isin([1,2,3])]
urban_nj.shape

(3918, 115)

In [ ]:
urban_nj.head(10)

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,VEHID,TRWAITTM,NUMTRANS,TRACCTM,DROP_PRK,TREGRTM,WHODROVE,WHYFROM,LOOP_TRIP,TRPHHVEH,HHMEMDRV,HH_ONTD,NONHHCNT,NUMONTRP,PSGR_FLG,PUBTRANS,TRIPPURP,DWELTIME,TDWKND,VMT_MILE,DRVR_FLG,WHYTRP1S,ONTD_P1,ONTD_P2,ONTD_P3,ONTD_P4,ONTD_P5,ONTD_P6,ONTD_P7,ONTD_P8,ONTD_P9,ONTD_P10,ONTD_P11,ONTD_P12,ONTD_P13,TDCASEID,TRACC_WLK,TRACC_POV,TRACC_BUS,TRACC_CRL,TRACC_SUB,TRACC_OTH,TREGR_WLK,TREGR_POV,TREGR_BUS,TREGR_CRL,TREGR_SUB,TREGR_OTH,WHYTO,TRAVDAY,HOMEOWN,HHSIZE,HHVEHCNT,HHFAMINC,DRVRCNT,HHSTATE,HHSTFIPS,NUMADLT,WRKCOUNT,TDAYDATE,HHRESP,LIF_CYC,MSACAT,MSASIZE,RAIL,URBAN,URBANSIZE,URBRUR,GASPRICE,CENSUS_D,CENSUS_R,CDIVMSAR,HH_RACE,HH_HISP,HH_CBSA,SMPLSRCE,R_AGE,EDUC,R_SEX,PRMACT,PROXY,WORKER,DRIVER,WTTRDFIN,WHYTRP90,TRPMILAD,R_AGE_IMP,R_SEX_IMP,VEHTYPE,OBHUR,DBHUR,OTHTNRNT,OTPPOPDN,OTRESDN,OTEEMPDN,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
909,30001262,1,1,750,800,10,0.649,3,1,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,1,2,2,2,HBSHOP,10,2,0.649,1,80,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,13,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,10,0.723700,58,1,1,C,C,30,7000,1500,3000,40,7000,3000,30,7000,1500,3000,40,7000,3000
910,30001262,1,2,810,825,15,17.391,3,1,0,1,-1,-1,-1,-1,-1,1,13,2,1,1,1,1,2,2,2,NHB,20,2,17.391,1,10,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,1,18.669238,58,1,1,C,T,30,7000,1500,3000,40,7000,3000,20,1500,300,750,5,750,300
911,30001262,1,3,845,855,10,9.203,3,1,0,1,-1,-1,-1,-1,-1,1,3,2,1,1,1,1,2,2,2,NHB,22,2,9.203,1,10,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620103,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,11,10.262265,58,1,1,T,C,20,1500,300,750,5,750,300,50,7000,1500,3000,90,7000,3000
912,30001262,1,4,917,923,6,5.742,3,1,0,1,-1,-1,-1,-1,-1,1,3,2,1,1,1,1,2,2,2,NHB,23,2,5.742,1,10,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620104,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,11,6.402904,58,1,1,C,S,50,7000,1500,3000,90,7000,3000,30,7000,1500,3000,40,3000,750
913,30001262,1,5,946,958,12,4.698,3,1,0,1,-1,-1,-1,-1,-1,1,3,2,1,1,1,1,2,2,2,NHB,10,2,4.698,1,10,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620105,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,11,5.238740,58,1,1,S,S,30,7000,1500,3000,40,3000,750,0,3000,750,1500,0,3000,750
914,30001262,1,6,1008,1032,24,4.407,3,1,0,1,-1,-1,-1,-1,-1,1,3,2,1,1,1,1,2,2,2,HBW,128,2,4.407,1,1,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620106,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,1,4.730914,58,1,1,S,C,0,3000,750,1500,0,3000,750,30,7000,1500,3000,40,7000,3000
915,30001262,1,7,1240,1248,8,1.673,3,1,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,1,2,2,2,HBSHOP,18,2,1.673,1,40,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620107,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,11,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,3,1.865562,58,1,1,C,C,30,7000,1500,3000,40,7000,3000,60,3000,750,1500,60,3000,750
916,30001262,1,8,1306,1308,2,1.892,3,1,0,1,-1,-1,-1,-1,-1,1,11,2,1,1,1,1,2,2,2,HBSHOP,184,2,1.892,1,1,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620108,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,3,2.109769,58,1,1,C,C,60,3000,750,1500,60,3000,750,30,7000,1500,3000,40,7000,3000
917,30001262,1,9,1612,1637,25,9.769,3,1,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,1,2,2,2,HBW,53,2,9.769,1,10,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620109,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,1,10.487022,58,1,1,C,S,30,7000,1500,3000,40,7000,3000,0,3000,1500,1500,5,3000,1500
918,30001262,1,10,1730,1736,6,0.368,3,1,0,1,-1,-1,-1,-1,-1,1,3,2,1,1,1,1,2,2,2,NHB,88,2,0.368,1,80,1,2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300012620110,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,13,3,2,2,2,6,2,NJ,34,2,2,201608,1,2,1,5,1,1,5,1,228.3,2,1,21,1,2,35620,1,58,4,1,1,1,1,1,1.083506e+06,10,0.410357,58,1,1,S,S,0,3000,1500,1500,5,3000,1500,5,3000,1500,1500,5,7000,1500

In [10]:
#function for filtering state and urban status from the dataset
def filter_state(df, state_code):
    state = df[df['HHSTFIPS'] == state_code]
    urban_state = state[state['URBAN'].isin([1,2,3])]
    return urban_state

In [11]:
urban_ny.head(10)

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,VEHID,TRWAITTM,NUMTRANS,TRACCTM,DROP_PRK,TREGRTM,WHODROVE,WHYFROM,LOOP_TRIP,TRPHHVEH,HHMEMDRV,HH_ONTD,NONHHCNT,NUMONTRP,PSGR_FLG,PUBTRANS,TRIPPURP,DWELTIME,TDWKND,VMT_MILE,DRVR_FLG,WHYTRP1S,ONTD_P1,ONTD_P2,ONTD_P3,ONTD_P4,ONTD_P5,ONTD_P6,ONTD_P7,ONTD_P8,ONTD_P9,ONTD_P10,ONTD_P11,ONTD_P12,ONTD_P13,TDCASEID,TRACC_WLK,TRACC_POV,TRACC_BUS,TRACC_CRL,TRACC_SUB,TRACC_OTH,TREGR_WLK,TREGR_POV,TREGR_BUS,TREGR_CRL,TREGR_SUB,TREGR_OTH,WHYTO,TRAVDAY,HOMEOWN,HHSIZE,HHVEHCNT,HHFAMINC,DRVRCNT,HHSTATE,HHSTFIPS,NUMADLT,WRKCOUNT,TDAYDATE,HHRESP,LIF_CYC,MSACAT,MSASIZE,RAIL,URBAN,URBANSIZE,URBRUR,GASPRICE,CENSUS_D,CENSUS_R,CDIVMSAR,HH_RACE,HH_HISP,HH_CBSA,SMPLSRCE,R_AGE,EDUC,R_SEX,PRMACT,PROXY,WORKER,DRIVER,WTTRDFIN,WHYTRP90,TRPMILAD,R_AGE_IMP,R_SEX_IMP,VEHTYPE,OBHUR,DBHUR,OTHTNRNT,OTPPOPDN,OTRESDN,OTEEMPDN,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
8,30000012,1,1,550,605,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,55,2,3.395,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,C,S,80,17000,17000,5000,60,17000,7000,30,750,300,350,5,750,300
9,30000012,1,2,700,715,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,16,2,1,1,1,0,1,2,2,HBSOCREC,15,2,3.395,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,S,C,30,750,300,350,5,750,300,80,17000,17000,5000,60,17000,7000
10,30000012,1,3,730,740,10,1.059,4,0,0,2,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,25,2,1.059,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120103,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,1.180891,45,2,3,C,C,80,17000,17000,5000,60,17000,7000,70,17000,7000,5000,90,3000,1500
11,30000012,1,4,805,815,10,1.014,4,0,0,2,-1,-1,-1,-1,-1,1,16,2,1,1,1,0,1,2,2,HBSOCREC,45,2,1.014,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120104,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,1.130711,45,2,3,C,C,70,17000,7000,5000,90,3000,1500,80,17000,17000,5000,60,17000,7000
12,30000012,1,5,900,920,20,4.291,3,0,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBW,295,2,4.291,1,10,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120105,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,2,4.784894,45,2,1,C,S,80,17000,17000,5000,60,17000,7000,20,1500,750,750,20,3000,1500
13,30000012,1,6,1415,1440,25,9.087,3,0,0,1,-1,-1,-1,-1,-1,1,4,2,1,1,1,0,1,2,2,NHB,50,2,9.087,1,10,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120106,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,3,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,1,9.754895,45,2,1,S,S,20,1500,750,750,20,3000,1500,20,1500,750,750,0,1500,750
14,30000012,1,7,1530,1605,35,6.818,3,0,0,1,-1,-1,-1,-1,-1,1,3,2,1,1,1,0,1,2,2,HBW,70,2,6.818,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120107,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,1,7.319123,45,2,1,S,C,20,1500,750,750,0,1500,750,80,17000,17000,5000,60,17000,7000
15,30000012,1,8,1715,1850,95,48.301,3,0,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,125,2,48.301,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120108,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,17,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,8,53.860445,45,2,1,C,T,80,17000,17000,5000,60,17000,7000,5,750,300,350,20,1500,750
16,30000012,1,9,2055,2145,50,49.457,3,0,0,1,-1,-1,-1,-1,-1,1,17,2,1,1,1,0,1,2,2,HBSOCREC,-9,2,49.457,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120109,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,8,55.149501,45,2,1,T,C,5,750,300,350,20,1500,750,80,17000,17000,5000,60,17000,7000
54,30000082,1,1,745,752,7,2.710,3,2,2,2,-1,-1,-1,-1,-1,1,1,2,1,1,3,0,3,2,2,HBO,17,2,2.710,1,70,1,2,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000820101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,6,3,2,4,2,8,2,NY,36,2,2,201605,1,4,3,3,2,1,3,1,241.3,2,1,23,1,2,XXXXX,2,39,5,2,1,1,1,1,375517.390495,4,3.021921,39,2,1,T,T,20,1500,300,750,30,750,300,40,1500,750,750,5,300,300

In [ ]:
urban_ny.isnull().sum()

#there are no missing values in the data

In [ ]:
urban_ny.describe()

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,VEHID,TRWAITTM,NUMTRANS,TRACCTM,DROP_PRK,TREGRTM,WHODROVE,WHYFROM,LOOP_TRIP,TRPHHVEH,HHMEMDRV,HH_ONTD,NONHHCNT,NUMONTRP,PSGR_FLG,PUBTRANS,DWELTIME,TDWKND,VMT_MILE,DRVR_FLG,WHYTRP1S,ONTD_P1,ONTD_P2,ONTD_P3,ONTD_P4,ONTD_P5,ONTD_P6,ONTD_P7,ONTD_P8,ONTD_P9,ONTD_P10,ONTD_P11,ONTD_P12,ONTD_P13,TDCASEID,TRACC_WLK,TRACC_POV,TRACC_BUS,TRACC_CRL,TRACC_SUB,TRACC_OTH,TREGR_WLK,TREGR_POV,TREGR_BUS,TREGR_CRL,TREGR_SUB,TREGR_OTH,WHYTO,TRAVDAY,HOMEOWN,HHSIZE,HHVEHCNT,HHFAMINC,DRVRCNT,HHSTFIPS,NUMADLT,WRKCOUNT,TDAYDATE,HHRESP,LIF_CYC,MSACAT,MSASIZE,RAIL,URBAN,URBANSIZE,URBRUR,GASPRICE,CENSUS_D,CENSUS_R,CDIVMSAR,HH_RACE,HH_HISP,SMPLSRCE,R_AGE,EDUC,R_SEX,PRMACT,PROXY,WORKER,DRIVER,WTTRDFIN,WHYTRP90,TRPMILAD,R_AGE_IMP,R_SEX_IMP,VEHTYPE,OTHTNRNT,OTPPOPDN,OTRESDN,OTEEMPDN,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
count,8.336900e+04,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.0,83369.0,83369.0,8.336900e+04,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.0,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,8.336900e+04,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000,83369.000000
mean,3.474054e+07,1.629623,3.325397,1349.167532,1378.038791,21.130180,9.814287,4.174201,0.792093,0.473929,4.931941,-0.612878,-0.940122,-0.597140,-0.993715,-0.472178,4.517507,7.540920,1.977606,1.248150,0.619007,1.473929,0.318164,1.792093,1.189435,1.963656,87.943120,1.707421,4.678627,0.763473,28.933596,1.272811,0.949921,0.018436,-0.412671,-0.775660,-0.925860,-0.964963,-0.985534,-0.993811,-0.997481,-1.0,-1.0,-1.0,3.474054e+11,-0.922873,-0.894817,-0.894517,-0.893174,-0.893989,-0.893426,-0.921290,-0.893905,-0.895093,-0.894037,-0.894361,-0.893546,7.519114,4.081181,1.875361,2.552448,1.899039,6.258441,1.838621,36.0,1.992071,1.258297,201637.490938,1.068023,5.583490,2.154746,3.708309,1.598268,1.146985,3.430052,1.000180,245.273406,2.000852,1.000660,22.163262,2.324557,1.938862,1.916624,49.968226,3.244371,1.516427,7.124255,1.220226,1.224784,0.950065,2.399546e+05,5.356655,10.562052,50.076131,1.526119,1.183773,33.944728,5529.003922,3381.587017,1685.240953,33.757776,5857.880531,3491.042138,33.932733,5520.334633,3373.097050,1684.508067,33.772170,5850.967290,3482.374648
std,5.027408e+06,0.918818,2.323778,424.810584,427.002714,30.888074,73.686244,5.509415,1.914311,0.835584,19.353124,2.667708,0.358441,3.898032,0.129343,4.789036,18.375389,7.467081,0.147963,0.431942,0.854617,0.835584,1.731225,1.914311,1.187466,0.187147,144.770487,0.454949,18.345334,0.981861,27.991582,0.445407,1.084873,1.302409,1.104718,0.745321,0.440118,0.308234,0.200055,0.132100,0.083083,0.0,0.0,0.0,5.027408e+10,0.421254,0.559126,0.560409,0.566118,0.562659,0.565052,0.430262,0.563016,0.557943,0.562455,0.561075,0.564544,7.460493,1.963070,7.862110,1.351433,1.124705,3.490792,0.853671,0.0,0.788342,0.983233,43.345434,0.304329,3.419473,1.046529,1.681837,0.490251,0.354601,1.854350,0.013412,9.890764,0.052632,0.035143,1.163515,10.410575,0.433371,0.276452,20.600036,1.637042,0.576190,20.223823,0.414401,0.796288,0.599786,4.205927e+05,3.600556,74.391981,20.464657,0.499320,1.648698,22.953721,8143.532747,6760.709071,1699.034258,25.694860,8221.655654,6679.609254,22.966462,8129.576966,6747.652304,1698.633267,25.704665,8209.207124,6663.137838
min,3.000001e+07,1.000000,1.000000,0.000000,0.000000,-9.000000,-9.000000,1.000000,0.000000,0.000000,-9.000000,-8.000000,-8.000000,-9.000000,-9.000000,-9.000000,-1.000000,-9.000000,1.000000,1.000000,-1.000000,1.000000,0.000000,1.000000,-1.000000,1.000000,-9.000000,1.000000,-1.000000,-1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,3.000001e+11,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,1.000000,-7.000000,1.000000,0.000000,-9.000000,0.000000,36.0,1.000000,0.000000,201604.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,228.300000,1.000000,1.000000,13.000000,-8.000000,-7.000000,1.000000,-8.000000,-8.000000,-8.000000,-7.000000,1.000000,-1.000000,-1.000000,5.299850e+03,1.000000,-9.000000,5.000000,1.000000,-8.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000,-9.000000
25%,3.025509e+07,1.000000,2.000000,1020.000000,1035.000000,7.000000,1.000000,3.000000,0.000000,0.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,2.000000,1.000000,1.000000,-1.000000,1.000000,1.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,3.025509e+11,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000,2.000000,1.000000,2.000000,1.000000,5.000000,1.000000,36.0,2.000000,0.000000,201608.000000,1.000000,2.000000,1.000000,3.000000,1.000000,1.000000,2.000000,1.000000,236.400000,2.000000,1.000000,21.000000,1.000000,2.000000,2.000000,35.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,2.548585e+04,3.000000,1.073841,35.000000,1.000000,-1.000000,20.000000,750.000000,300.000000,350.000000,5.000000,750.000000,300.000000,20.000000,750.000000,300.000000,350.000000,5.000000,750.000000,300.000000
50%,3.049659e+07,1.000000,3.000000,1340.000000,1400.000000,15.000000,2.727000,3.000000,0.000000,0.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,1.000000,6.000000,2.000000,1.000000,1.000000,1.000000,0.000000,1.000000,2.000000,2.000000,27.000000,2.000000,1.101000,1.000000,20.000000,1.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,3.049659e+11,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,6.000000,4.000000,1.000000,2.000000,2.000000,7.000000,2.000000,36.0,2.000000,1.000000,201610.000000,1.000000,6.000000,2.000000,4.000000,2.000000,1.000000,3.000000,1.000000,244.700000,2.000000,1.000000,22.000000,1.000000,2.000000,2.000000,54.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,6.546692e+04,4.000000,2.997389,54.000000,2.000000,1.000000,30.000000,3000.000000,750.000000,750.000000,30.000000,3000.000000,1500.000000,30.000000,3000.000000,750.000000,750.000000,30.000000,3000.000000,1500.000000
75%,4.033861e+07,2.000000,4.000000,1700.000000,1715.000000,25.000000,7.107000,4.000000,1.000000,1.000000,2.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,2.000000,13.000000,2.000000,1.000000,1.000000,2.000000,0.000000,2.000000,2.000000,2.000000,105.000000,2.000000,4.450000,1.000000,50.000000,2.000000,2.000000,1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.0,-1.0,-1.0,4.033861e+11,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,13.000000,6.000000,1.000000,3.000000,2.000000,8.000000,2.000000,36.0,2.000000,2.000000,201701.000000,1.000000,9.000000,3.000000,5.000000,2.000000,1.000000,5.000000,1.000000,253.000000,2.000000,1.000000,23.000000,1.000000,2.000000,2.000000,65.000000,5.000000,2.000000,6.000000,1.000000,2.000000,1.000000,2.073551e+05,10.000000,7.828002,66.000000,2.000000,3.000000,50.000000,7000.000000,3000.000000,3000.000000,50.000000,7000.000000,3000.000000,50.000000,7000.000000,3000.000000,3000.000000,50.000000,7000.000000,3000.000000
max,4.079425e+07,10.000000,23.000000,2359.000000,2359.000000,960.000000,9621.053000,97.000000,156.000000,8.000000,97.000000,77.000000,10.000000,300.000000,3.000000,180.000000,97.000000,97.000000,2.000000,2.000000,2.000000,9.000000,156.000000,157.000000,2.000000,2.000000,1240.000000,2.000000,1272.702000,2.000000,97.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,-1.0,-1.0,-1.0,4.079425e+11,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,97.000000,7.000000,97.000000,10.000000,11.000000,11.000000,7.000000,36.0,10.000000,7.000000,201704.000000,5.000000,10.000000,4.000000,6.000000,2.000000,3.000000,6.000000,2.000000,264.900000,5.000000,3.000000,52.000000,97.000000,2.000000,2.000000,92.000000,5.000000,2.000000,97.000000,2.000000,2.000000,2.000000,4.103964e+06,99.000000,9621.053000,92.000000,2.000000,97.000000,95.000000,30000.000000,30000.000000,5000.000000,95.000000,30000.000000,30000.000000,95.000000,30000.000000,30000.000000,5000.000000,95.000000,30000.000000,30000.000000

In [ ]:
#unique values in household column
urban_ny['HOUSEID'].nunique()

10698

In [ ]:
urban_ny.head(5)

,HOUSEID,PERSONID,TDTRPNUM,STRTTIME,ENDTIME,TRVLCMIN,TRPMILES,TRPTRANS,TRPACCMP,TRPHHACC,VEHID,TRWAITTM,NUMTRANS,TRACCTM,DROP_PRK,TREGRTM,WHODROVE,WHYFROM,LOOP_TRIP,TRPHHVEH,HHMEMDRV,HH_ONTD,NONHHCNT,NUMONTRP,PSGR_FLG,PUBTRANS,TRIPPURP,DWELTIME,TDWKND,VMT_MILE,DRVR_FLG,WHYTRP1S,ONTD_P1,ONTD_P2,ONTD_P3,ONTD_P4,ONTD_P5,ONTD_P6,ONTD_P7,ONTD_P8,ONTD_P9,ONTD_P10,ONTD_P11,ONTD_P12,ONTD_P13,TDCASEID,TRACC_WLK,TRACC_POV,TRACC_BUS,TRACC_CRL,TRACC_SUB,TRACC_OTH,TREGR_WLK,TREGR_POV,TREGR_BUS,TREGR_CRL,TREGR_SUB,TREGR_OTH,WHYTO,TRAVDAY,HOMEOWN,HHSIZE,HHVEHCNT,HHFAMINC,DRVRCNT,HHSTATE,HHSTFIPS,NUMADLT,WRKCOUNT,TDAYDATE,HHRESP,LIF_CYC,MSACAT,MSASIZE,RAIL,URBAN,URBANSIZE,URBRUR,GASPRICE,CENSUS_D,CENSUS_R,CDIVMSAR,HH_RACE,HH_HISP,HH_CBSA,SMPLSRCE,R_AGE,EDUC,R_SEX,PRMACT,PROXY,WORKER,DRIVER,WTTRDFIN,WHYTRP90,TRPMILAD,R_AGE_IMP,R_SEX_IMP,VEHTYPE,OBHUR,DBHUR,OTHTNRNT,OTPPOPDN,OTRESDN,OTEEMPDN,OBHTNRNT,OBPPOPDN,OBRESDN,DTHTNRNT,DTPPOPDN,DTRESDN,DTEEMPDN,DBHTNRNT,DBPPOPDN,DBRESDN
8,30000012,1,1,550,605,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,55,2,3.395,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120101,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,C,S,80,17000,17000,5000,60,17000,7000,30,750,300,350,5,750,300
9,30000012,1,2,700,715,15,3.395,4,0,0,2,-1,-1,-1,-1,-1,1,16,2,1,1,1,0,1,2,2,HBSOCREC,15,2,3.395,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120102,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,3.785764,45,2,3,S,C,30,750,300,350,5,750,300,80,17000,17000,5000,60,17000,7000
10,30000012,1,3,730,740,10,1.059,4,0,0,2,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBSOCREC,25,2,1.059,1,50,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120103,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,16,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,1.180891,45,2,3,C,C,80,17000,17000,5000,60,17000,7000,70,17000,7000,5000,90,3000,1500
11,30000012,1,4,805,815,10,1.014,4,0,0,2,-1,-1,-1,-1,-1,1,16,2,1,1,1,0,1,2,2,HBSOCREC,45,2,1.014,1,1,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120104,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,1,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,10,1.130711,45,2,3,C,C,70,17000,7000,5000,90,3000,1500,80,17000,17000,5000,60,17000,7000
12,30000012,1,5,900,920,20,4.291,3,0,0,1,-1,-1,-1,-1,-1,1,1,2,1,1,1,0,1,2,2,HBW,295,2,4.291,1,10,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,300000120105,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,4,5,1,1,2,10,1,NY,36,1,1,201607,1,1,3,3,2,1,3,1,233.8,2,1,23,1,2,XXXXX,2,45,5,2,1,1,1,1,21522.690513,2,4.784894,45,2,1,C,S,80,17000,17000,5000,60,17000,7000,20,1500,750,750,20,3000,1500

In [35]:
#columns need for the analysis
req_col = ['HOUSEID', 'PERSONID', 'STRTTIME', 'ENDTIME', 
           'TRVLCMIN', 'WHYFROM', 'WHYTO', 'WHYTRP1S']

In [36]:
#creating a new dataframe with required columns
new_df = urban_ny[req_col]

In [61]:
new_df.head(5)

     HOUSEID  PERSONID STRTTIME ENDTIME  TRVLCMIN  WHYFROM  WHYTO  WHYTRP1S
8   30000012         1     5:50    6:05        15        1     16        50
9   30000012         1     7:00    7:15        15       16      1         1
10  30000012         1     7:30    7:40        10        1     16        50
11  30000012         1     8:05    8:15        10       16      1         1
12  30000012         1     9:00    9:20        20        1      4        10

### activity chain 
##### activity and their code as per 'WHYTRP1S'
- H: in home             - 01
- W: work                - 10
- M: maintenance         - 30
- S: School              - 20
- K: pickup/drop off     - 70
- O: other               - 97
- R: recreational/social - 50
- P: personal activities - 40

In [ ]:
# class Household:
#     def __init__(self, data):
#         self.data = data
    
#     def create_activity_chain(self):
#         # Define time slots from 06:00 to 23:00 with a duration of 15 minutes
#         time_slots = pd.date_range(start='06:00', end='23:00', freq='15min').time
        
#         activity_chains = []
        
#         for index, row in self.data.iterrows():
#             # Initialize activity chain for the current individual
#             activity_chain = ''
            
#             # Iterate through each time slot
#             for time_slot in time_slots:
#                 # Check if the current time slot falls within the trip start and end time
#                 if row['STRTTIME'].time() <= time_slot < row['ENDTIME'].time():
#                     # Assign activity category based on trip purpose summary
#                     if row['WHYTRP1S'] in ['E', 'J', 'N']:
#                         activity_chain += 'H'  # In-home
#                     elif row['WHYTRP1S'] in ['B', 'C', 'D', 'F', 'G', 'L', 'Q', 'T', 'U', 'V']:
#                         activity_chain += 'M'  # Maintenance
#                     elif row['WHYTRP1S'] in ['A']:
#                         activity_chain += 'K'  # Pickup/drop off
#                     elif row['WHYTRP1S'] in ['P', 'R']:
#                         activity_chain += 'R'  # Recreational/social
#                     elif row['WHYTRP1S'] in ['I']:
#                         activity_chain += 'W'  # Work
#                     elif row['WHYTRP1S'] in ['S']:
#                         activity_chain += 'S'  # School
#                     else:
#                         activity_chain += 'O'  # Other
            
#             # Append the activity chain to the list
#             activity_chains.append(activity_chain)
        
#         # Add the activity chains to the DataFrame
#         self.data['Activity_Chain'] = activity_chains
        
#         return self.data[['HOUSEID', 'PERSONID', 'Activity_Chain']]

# # Filter the required columns
# required_data = new_df[req_col]

# # Create an instance of the Household class
# household = Household(required_data)

# # Create activity chains for each individual
# activity_chains = household.create_activity_chain()

# # Display the DataFrame with activity chains
# print(activity_chains)

In [39]:
class Household:
    def __init__(self, data):
        self.data = data
    
    def generate_activity_chain(self):
        activity_chains = []
        
        for index, row in self.data.iterrows():
            start_time = row['STRTTIME']
            end_time = row['ENDTIME']
            duration = (end_time - start_time).seconds // 60  # Convert duration to minutes
            
            activity_chain = ''
            for i in range(6, 23, 15):  # Loop through time slots from 06:00 to 23:00
                slot_start = start_time.replace(hour=i, minute=0, second=0)
                slot_end = start_time.replace(hour=i+15, minute=0, second=0)
                
                if start_time <= slot_start < end_time or start_time < slot_end <= end_time:
                    if row['WHYFROM'] == '01' and row['WHYTO'] == '01':
                        activity_chain += 'H'  # In home
                    elif row['WHYTRP1S'] == '10':
                        activity_chain += 'W'  # Work
                    elif row['WHYTRP1S'] == '30':
                        activity_chain += 'M'  # Maintenance
                    elif row['WHYTRP1S'] == '20':
                        activity_chain += 'S'  # School
                    elif row['WHYTRP1S'] == '70':
                        activity_chain += 'K'  # Pick up/Drop off
                    elif row['WHYTRP1S'] == '50':
                        activity_chain += 'R'  # Recreational/Social
                    elif row['WHYTRP1S'] == '40':
                        activity_chain += 'P'  # Personal activities
                    else:
                        activity_chain += 'O'  # Other
            
            activity_chains.append(activity_chain)

In [52]:
def convert_time(time_int):
    time_str = str(time_int)
    return time_str[:-2] + ':' + time_str[-2:]

#converitng the time to string
new_df['STRTTIME'] = new_df['STRTTIME'].apply(convert_time)
new_df['ENDTIME'] = new_df['ENDTIME'].apply(convert_time)

In [51]:
new_df.head(10)

     HOUSEID  PERSONID STRTTIME ENDTIME  TRVLCMIN  WHYFROM  WHYTO  WHYTRP1S
8   30000012         1     5:50    6:05        15        1     16        50
9   30000012         1     7:00    7:15        15       16      1         1
10  30000012         1     7:30    7:40        10        1     16        50
11  30000012         1     8:05    8:15        10       16      1         1
12  30000012         1     9:00    9:20        20        1      4        10
13  30000012         1    14:15   14:40        25        4      3        10
14  30000012         1    15:30   16:05        35        3      1         1
15  30000012         1    17:15   18:50        95        1     17        50
16  30000012         1    20:55   21:45        50       17      1         1
54  30000082         1     7:45    7:52         7        1      6        70

In [64]:
from datetime import datetime

def convert_to_datetime(time_str):
    return datetime.strptime(time_str, '%H:%M')

# Convert STRTTIME and ENDTIME to datetime objects
new_df['STRTTIME'] = new_df['STRTTIME'].apply(convert_to_datetime)
new_df['ENDTIME'] = new_df['ENDTIME'].apply(convert_to_datetime)

# Define a function to categorize activities
def categorize_activity(row):
    if row['WHYFROM'] == 1 and row['WHYTO'] == 1:
        return 'H'  # In-home activities
    elif row['WHYTRP1S'] == 1:
        return 'W'  # Work-related activities
    elif row['WHYTRP1S'] == 30:
        return 'M'  # Maintenance activities
    elif row['WHYTRP1S'] == 20:
        return 'S'  # School activities
    elif row['WHYTRP1S'] == 70:
        return 'K'  # Pick up/Drop off activities
    elif row['WHYTRP1S'] == 50:
        return 'R'  # Recreational/Social activities
    elif row['WHYTRP1S'] == 40:
        return 'P'  # Personal activities
    else:
        return 'O'  # Other activities

# Apply the categorize_activity function to create the Activity Chain column
df['Activity Chain'] = df.apply(categorize_activity, axis=1)

# Display the DataFrame with the Activity Chain column
print(df[['HOUSEID', 'PERSONID', 'STRTTIME', 'ENDTIME', 'Activity Chain']])

ValueError: time data ':10' does not match format '%H:%M'

In [ ]:
# CENSUS_D
#  - New England (Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont)
#  - Middle Atlantic (New Jersey, New York, Pennsylvania)
#  - East North Central (Illinois, Indiana, Michigan, Ohio, Wisconsin)
#  - West North Central (Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, South Dakota)
#  - South Atlantic (Delaware, Florida, Georgia, Maryland, North Carolina, South Carolina, Virginia, West Virginia, District of Columbia)
#  - East South Central (Alabama, Kentucky, Mississippi, Tennessee)
#  - West South Central (Arkansas, Louisiana, Oklahoma, Texas)
#  - Mountain (Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah, Wyoming)
#  - Pacific (Alaska, California, Hawaii, Oregon, Washington)


# CENSUS_R
#  - Northeast (Connecticut, Maine, Massachusetts, New Hampshire, Rhode Island, Vermont, New Jersey, New York, Pennsylvania)
#  - midwest (Illinois, Indiana, Michigan, Ohio, Wisconsin, Iowa, Kansas, Minnesota, Missouri, Nebraska, North Dakota, South Dakota)
#  - south (Delaware, Florida, Georgia, Maryland, North Carolina, South Carolina, Virginia, West Virginia, District of Columbia, Alabama, Kentucky, Mississippi, Tennessee, Arkansas, Louisiana, Oklahoma, Texas)
#  - west (Arizona, Colorado, Idaho, Montana, Nevada, New Mexico, Utah, Wyoming, Alaska, California, Hawaii, Oregon, Washington)

In [4]:
from datetime import datetime

time_str = '550'

hour = int(time_str[:-2])  
minute = int(time_str[-2:])

time_date = datetime.now().replace(hour=hour, minute=minute, second=0, microsecond=0)

# Print the converted time string
print("Converted Time:", time_date)

Converted Time: 2024-03-11 05:50:00

In [5]:
type(time_date)

datetime.datetime

In [7]:
urban_ny['CENSUS_D'].unique()

NameError: name 'urban_ny' is not defined